---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: foo
  labels: 
    app: nginx
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: whyevenquestion1t/rin-nginx:v.0.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "1"
        ports:
        - containerPort: 80
